"""Generate methodology.pdf for SuPerator submissions.

Priority: fpdf2 if available, else raw PDF bytes (dependency-free minimal PDF).
No API key, no config.yaml, no LLM, no remote calls.
Output writes to outputs/submission/submission/ (git-ignored).
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

# ---------------------------------------------------------------------------
# Unicode → ASCII sanitization
# ---------------------------------------------------------------------------

_UNICODE_REPLACEMENTS: dict[int, str] = {
    0x2014: "-",   # — (em dash)
    0x2013: "-",   # – (en dash)
    0x2018: "'",   # ' (left single quote)
    0x2019: "'",   # ' (right single quote)
    0x201C: '"',   # " (left double quote)
    0x201D: '"',   # " (right double quote)
    0x2192: "->",  # → (right arrow)
    0x00D7: "x",   # × (multiplication)
    0x2264: "<=",  # ≤
    0x2265: ">=",  # ≥
    0x2026: "...", # …
    0x00B7: "*",   # · (middle dot)
    0x2212: "-",   # − (minus sign)
    0x00A0: " ",   # non-breaking space
}


def sanitize_pdf_text(text: str) -> str:
    """Replace Unicode characters unsupported by PDF built-in fonts with ASCII.

    Helvetica/Courier fonts only support WinAnsiEncoding (cp1252 subset).
    Characters outside this range cause fpdf2 to raise an error.
    """
    result: list[str] = []
    for ch in text:
        cp = ord(ch)
        if cp in _UNICODE_REPLACEMENTS:
            result.append(_UNICODE_REPLACEMENTS[cp])
        elif cp < 128:
            result.append(ch)
        elif 160 <= cp <= 255:
            # cp1252 upper range — may or may not be in the font
            # Keep them if printable
            result.append(ch)
        else:
            # Drop characters outside the safe range
            result.append("?")
    return "".join(result)


_METHODOLOGY_CONTENT_EN = [
    ("SuPerator Methodology Summary", "h1"),
    ("", "blank"),
    ("Overview", "h2"),
    ("SuPerator is an AI4S PDE neural operator research-agent engineering project. "
     "This submission is generated by the pdeagent adapter workflow within SuPerator, "
     "using clean-room implementations of FNO-based models adapted from the pdeagent baseline.", "p"),
    ("", "blank"),
    ("Workflow", "h2"),
    ("Local-first PDE neural operator workflow: config-driven training, "
     "checkpoint-based inference, and automated submission packaging. "
     "All training and inference runs locally without remote compute backends.", "p"),
    ("", "blank"),
    ("Task 1 - Fixed Nu Burgers", "h2"),
    ("Burgers equation with fixed viscosity nu=0.001. ChunkedFNO1d model (SpectralConv1d + "
     "FNOBlock1d stack) with autoregressive chunk rollout. "
     "Sliding-window training on official Task 1 validation data. "
     "Prediction shape: (N, 200, 256). 3-segment scoring.", "p"),
    ("", "blank"),
    ("Task 2 - Varying Nu Burgers", "h2"),
    ("Burgers equation with varying viscosity. ChunkedFNO1d + FiLM conditioning "
     "+ NuEstimator1d for test-time viscosity inference from initial conditions. "
     "Training uses provided Nu values; inference estimates Nu without test Nu dependency. "
     "Prediction shape: (N, 200, 256). Inference within 120s hard limit.", "p"),
    ("", "blank"),
    ("Adapter Source", "h2"),
    ("Model architecture adapted from pdeagent baseline (external_references/pdeagent_code_ref/). "
     "Clean-room implementation in src/adapters/pdeagent/. "
     "No pretrained models used. Task 2 trained from scratch with Task 2 data only.", "p"),
    ("", "blank"),
    ("Validation", "h2"),
    ("All predictions validated: shape (N, 200, 256), first 10 steps match initial conditions "
     "(max error < 1e-3), finite values, JSONL task logs, time.csv format. "
     "Code bundle validated: no prohibited content.", "p"),
    ("", "blank"),
    ("Logs", "h2"),
    ("Task logs are JSON Lines format with timezone-aware ISO 8601 timestamps, "
     "non-negative elapsed_seconds, and response/tool_calls content. "
     "Logs use development_summary_log provenance mode. "
     "These logs are structurally valid but are not complete API-proxy LLM call logs.", "p"),
    ("", "blank"),
    ("Code Bundle", "h2"),
    ("The code/ directory contains runnable source code, configs, and scripts "
     "corresponding to the recorded agent log history. "
     "No .agents/, strategy docs, datasets, checkpoints, or API keys included.", "p"),
    ("", "blank"),
    ("No API key or credential included in this submission.", "p"),
]


def _build_methodology_lines(
    submission_id: str = "SuPerator",
    tasks: list[str] | None = None,
    backend_summary: dict[str, Any] | None = None,
    log_provenance_note: str | None = None,
    include_agent_summary: bool = True,
) -> list[tuple[str, str]]:
    """Build the methodology content lines."""
    lines: list[tuple[str, str]] = list(_METHODOLOGY_CONTENT_EN)

    if tasks:
        lines.insert(0, ("Tasks: " + ", ".join(tasks), "p"))

    if backend_summary:
        lines.append(("Compute Backend", "h2"))
        for k, v in backend_summary.items():
            lines.append((f"{k}: {v}", "p"))

    if log_provenance_note:
        lines.append(("Log Provenance Note", "h2"))
        lines.append((log_provenance_note, "p"))

    return lines


# ---------------------------------------------------------------------------
# fpdf2-based PDF generation
# ---------------------------------------------------------------------------

def _create_pdf_fpdf(
    output_path: Path,
    lines: list[tuple[str, str]],
    submission_id: str,
) -> None:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    for text, style in lines:
        safe_text = sanitize_pdf_text(text)
        if style == "h1":
            pdf.set_font("Helvetica", "B", 16)
            pdf.cell(0, 10, safe_text, new_x="LMARGIN", new_y="NEXT", align="C")
        elif style == "h2":
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, safe_text, new_x="LMARGIN", new_y="NEXT")
        elif style == "blank":
            pdf.ln(3)
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 5, safe_text)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))


# ---------------------------------------------------------------------------
# Dependency-free raw PDF generation
# ---------------------------------------------------------------------------

def _escape_pdf_string(s: str) -> str:
    """Escape a string for PDF literal string."""
    s = s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
    # Keep only ASCII printable + newline
    result = []
    for ch in s:
        if 32 <= ord(ch) <= 126 or ch == "\n":
            result.append(ch)
    return "".join(result)


def _create_pdf_raw(
    output_path: Path,
    lines: list[tuple[str, str]],
    submission_id: str,
) -> None:
    """Generate a minimal valid PDF using raw bytes. No external dependencies."""
    import textwrap

    # Build text content
    text_lines: list[str] = []
    for text, style in lines:
        if style == "blank":
            text_lines.append("")
        elif style == "h1":
            text_lines.append("")
            text_lines.append(text.upper())
            text_lines.append("=" * min(len(text), 60))
        elif style == "h2":
            text_lines.append("")
            text_lines.append(text)
            text_lines.append("-" * min(len(text), 40))
        else:
            wrapped = textwrap.wrap(text, width=90)
            for w in wrapped:
                text_lines.append(w)
            if not wrapped:
                text_lines.append("")

    pdf_text = "\n".join(text_lines)

    # Build PDF content stream
    stream_lines: list[bytes] = [
        b"BT",
        b"/F1 10 Tf",
        b"50 750 Td",
        b"12 TL",
    ]
    for line in pdf_text.split("\n")[:120]:
        safe = _escape_pdf_string(line)
        stream_lines.append(f"({safe}) T*".encode("ascii", errors="replace"))
    stream_lines.append(b"ET")

    stream_body = b"\n".join(stream_lines) + b"\n"
    stream_len = len(stream_body)

    # Build all PDF objects as a byte list, tracking offsets
    header = b"%PDF-1.4\n"
    pdf_parts: list[bytes] = [header]

    def add_obj(obj_bytes: bytes) -> None:
        pdf_parts.append(obj_bytes)

    # Figure 1: Catalog
    add_obj(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
    # Object 2: Pages
    add_obj(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")
    # Object 3: Page
    add_obj(b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n")
    # Object 4: Content stream
    stream_obj = (
        f"4 0 obj\n<< /Length {stream_len} >>\nstream\n".encode()
        + stream_body
        + b"endstream\nendobj\n"
    )
    add_obj(stream_obj)
    # Object 5: Font
    add_obj(b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n")

    # Compute byte offsets for xref
    offsets: list[int] = []
    pos = 0
    for i, part in enumerate(pdf_parts):
        if i >= 1:  # skip header for offsets (xref references after header)
            offsets.append(pos)
        pos += len(part)

    n_objects = len(offsets)
    xref_offset = pos  # position where xref starts

    # Build xref
    xref_lines: list[bytes] = [b"xref"]
    xref_lines.append(f"0 {n_objects + 1}".encode())
    xref_lines.append(b"0000000000 65535 f ")
    for off in offsets:
        xref_lines.append(f"{off:010d} 00000 n ".encode())
    xref_body = b"\n".join(xref_lines) + b"\n"

    # Build trailer
    trailer = (
        b"trailer\n"
        + f"<< /Size {n_objects + 1} /Root 1 0 R >>\n".encode()
        + b"startxref\n"
        + f"{xref_offset}\n".encode()
        + b"%%EOF\n"
    )

    # Write
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "wb") as f:
        for part in pdf_parts:
            f.write(part)
        f.write(xref_body)
        f.write(trailer)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def create_methodology_pdf(
    output_path: str | Path,
    *,
    submission_id: str = "SuPerator",
    tasks: list[str] | None = None,
    backend_summary: dict[str, Any] | None = None,
    log_provenance_note: str | None = None,
    include_agent_summary: bool = True,
) -> Path:
    """Create methodology.pdf for a SuPerator submission.

    Args:
        output_path: Where to write methodology.pdf.
        submission_id: Identifier for this submission.
        tasks: List of task names, e.g. ["task1", "task2"].
        backend_summary: Optional dict of compute backend info.
        log_provenance_note: Optional provenance note.
        include_agent_summary: Whether to include the standard methodology text.

    Returns:
        Path to the generated PDF file.

    Raises:
        RuntimeError: If PDF generation fails and no file was written.
    """
    path = Path(output_path)

    lines = _build_methodology_lines(
        submission_id=submission_id,
        tasks=tasks,
        backend_summary=backend_summary,
        log_provenance_note=log_provenance_note,
        include_agent_summary=include_agent_summary,
    )

    # Try fpdf2 first
    try:
        import fpdf  # noqa: F401
        _create_pdf_fpdf(path, lines, submission_id)
        return path
    except (ImportError, ModuleNotFoundError):
        pass
    except Exception:
        # Any runtime error (e.g. font encoding) → fallback to raw PDF
        import traceback
        traceback.print_exc()
        print("[WARN] fpdf2 generation failed, falling back to raw PDF")

    # Fallback: raw PDF bytes (always works, no external deps)
    _create_pdf_raw(path, lines, submission_id)
    return path
