"""Evaluate a Task 1 persistence baseline on validation data."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import h5py
import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.hdf5_utils import find_main_array_key
from src.eval.task1_metrics import persistence_baseline_from_full, rel_mse, rmse, segmented_score


CONFIG_PATH = ROOT / "configs" / "task1_baseline.yaml"
DOC_PATH = ROOT / "docs" / "task1_persistence_baseline.md"


def resolve_path(path_value: str | Path) -> Path:
    path = Path(path_value)
    return path if path.is_absolute() else ROOT / path


def normalize_key(key: str) -> str:
    return key[1:] if key.startswith("/") else key


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as config_file:
        config = yaml.safe_load(config_file)
    if not isinstance(config, dict):
        raise ValueError(f"Config must be a mapping: {path}")
    return config


def evaluate() -> dict[str, Any]:
    config = load_config()
    data_config = config["data"]
    val_path = resolve_path(data_config["val_path"])
    input_steps = int(data_config["input_steps"])
    total_steps = int(data_config["total_steps"])
    key = data_config.get("hdf5_key") or find_main_array_key(val_path)

    with h5py.File(val_path, "r") as h5_file:
        dataset = h5_file[normalize_key(key)]
        shape = tuple(dataset.shape)
        dtype = str(dataset.dtype)
        if len(shape) != 3:
            message = f"Skipping persistence evaluation: expected 3D data, got {shape}."
            result = {"status": "skipped", "reason": message, "key": key, "shape": shape, "dtype": dtype}
        elif shape[1] >= total_steps:
            full = dataset[:, :total_steps, :]
            pred = persistence_baseline_from_full(full, input_steps=input_steps, total_steps=total_steps)
            metrics = segmented_score(pred, full)
            result = {
                "status": "ok",
                "key": key,
                "shape": shape,
                "dtype": dtype,
                "metrics": metrics,
            }
        elif shape[1] > input_steps:
            full = dataset[:, :, :]
            pred = persistence_baseline_from_full(full, input_steps=input_steps, total_steps=shape[1])
            result = {
                "status": "partial",
                "reason": (
                    f"Validation data has {shape[1]} time steps; segmented score needs "
                    f"{total_steps}. Reporting basic errors only."
                ),
                "key": key,
                "shape": shape,
                "dtype": dtype,
                "rel_mse_after_input": rel_mse(pred[:, input_steps:, :], full[:, input_steps:, :]),
                "rmse_after_input": rmse(pred[:, input_steps:, :], full[:, input_steps:, :]),
            }
        else:
            message = (
                f"Skipping persistence evaluation: validation data has {shape[1]} time steps; "
                f"need more than {input_steps}."
            )
            result = {"status": "skipped", "reason": message, "key": key, "shape": shape, "dtype": dtype}
    return result


def format_report(result: dict[str, Any]) -> str:
    lines = [
        "# Task 1 Persistence Baseline",
        "",
        "Generated by `python scripts/evaluate_persistence_task1.py`.",
        "",
        f"- Status: `{result['status']}`",
        f"- Main key: `{result.get('key')}`",
        f"- Shape: `{result.get('shape')}`",
        f"- Dtype: `{result.get('dtype')}`",
    ]
    if "reason" in result:
        lines.append(f"- Note: {result['reason']}")
    metrics = result.get("metrics")
    if isinstance(metrics, dict):
        lines.append("")
        lines.append("## Metrics")
        lines.append("")
        for key, value in metrics.items():
            lines.append(f"- `{key}`: {value}")
    else:
        for key in ["rel_mse_after_input", "rmse_after_input"]:
            if key in result:
                lines.append(f"- `{key}`: {result[key]}")
    lines.append("")
    return "\n".join(lines)


def main() -> dict[str, Any]:
    result = evaluate()
    report = format_report(result)
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(report, encoding="utf-8")
    print(json.dumps(result, indent=2, default=str))
    print(f"Wrote {DOC_PATH.relative_to(ROOT)}")
    return result


if __name__ == "__main__":
    main()
