"""Inspect local task_log_sample/ materials and write a compact inventory."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SAMPLE_DIR = ROOT / "task_log_sample"
OUTPUT_PATH = ROOT / "docs" / "task_log_sample_inventory.md"
TEXT_SUFFIXES = {".log", ".txt", ".json", ".md", ".csv"}
PREVIEW_LINES = 6
PREVIEW_CHARS = 240


def _read_lines(path: Path) -> list[str]:
    for encoding in ("utf-8", "utf-8-sig", "gb18030"):
        try:
            return path.read_text(encoding=encoding).splitlines()
        except UnicodeDecodeError:
            continue
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def _summarize_file(path: Path) -> list[str]:
    relative = path.relative_to(ROOT).as_posix()
    size = path.stat().st_size
    lines = [f"### `{relative}`", "", f"- Size: {size} bytes"]
    if path.suffix.lower() in TEXT_SUFFIXES:
        content_lines = _read_lines(path)
        lines.append(f"- Lines: {len(content_lines)}")
        lines.append("- Preview:")
        for line in content_lines[:PREVIEW_LINES]:
            preview = line[:PREVIEW_CHARS]
            if len(line) > PREVIEW_CHARS:
                preview += " ..."
            lines.append(f"  - `{preview}`")
    else:
        lines.append("- Preview: skipped for unknown or binary suffix")
    lines.append("")
    return lines


def build_inventory() -> str:
    if not SAMPLE_DIR.is_dir():
        raise FileNotFoundError(f"Required task log sample directory is missing: {SAMPLE_DIR}")

    paths = sorted(path for path in SAMPLE_DIR.rglob("*") if path.is_file())
    lines = [
        "# Task Log Sample Inventory",
        "",
        "Generated by `scripts/inspect_task_log_sample.py`.",
        "",
        "This inventory summarizes local official sample materials without copying long log content.",
        "",
        "## Files",
        "",
    ]
    for path in paths:
        lines.extend(_summarize_file(path))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    inventory = build_inventory()
    print(inventory)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(inventory, encoding="utf-8")
    print(f"Wrote inventory: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
