"""Inspect Task 1 HDF5 files without loading large arrays."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import h5py
import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.hdf5_utils import find_main_array_key, list_hdf5_structure


CONFIG_PATH = ROOT / "configs" / "task1_baseline.yaml"
DOC_PATH = ROOT / "docs" / "task1_hdf5_inventory.md"


def resolve_path(path_value: str | Path) -> Path:
    path = Path(path_value)
    return path if path.is_absolute() else ROOT / path


def normalize_key(key: str) -> str:
    return key[1:] if key.startswith("/") else key


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as config_file:
        config = yaml.safe_load(config_file)
    if not isinstance(config, dict):
        raise ValueError(f"Config must be a mapping: {path}")
    return config


def inspect_file(label: str, path: Path, key: str | None) -> dict[str, Any]:
    structure = list_hdf5_structure(path)
    main_key = key or find_main_array_key(path)
    with h5py.File(path, "r") as h5_file:
        dataset = h5_file[normalize_key(main_key)]
        shape = tuple(dataset.shape)
        dtype = str(dataset.dtype)
    return {
        "label": label,
        "path": path,
        "structure": structure,
        "main_key": main_key,
        "shape": shape,
        "dtype": dtype,
    }


def format_report(results: list[dict[str, Any]]) -> str:
    lines = [
        "# Task 1 HDF5 Inventory",
        "",
        "Generated by `python scripts/inspect_task1_hdf5.py`.",
        "",
    ]
    for result in results:
        lines.extend(
            [
                f"## {result['label']}",
                "",
                f"- Path: `{result['path'].relative_to(ROOT)}`",
                f"- Main key: `{result['main_key']}`",
                f"- Main shape: `{result['shape']}`",
                f"- Main dtype: `{result['dtype']}`",
                "",
                "### Structure",
                "",
            ]
        )
        for entry in result["structure"]:
            lines.append(
                f"- `{entry['key']}`: type={entry['type']}, "
                f"shape={entry['shape']}, dtype={entry['dtype']}"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> list[dict[str, Any]]:
    config = load_config()
    data_config = config["data"]
    key = data_config.get("hdf5_key")
    results = [
        inspect_file("task1_val.hdf5", resolve_path(data_config["val_path"]), key),
        inspect_file("task1_test.hdf5", resolve_path(data_config["test_path"]), key),
    ]
    report = format_report(results)
    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOC_PATH.write_text(report + "\n", encoding="utf-8")

    for result in results:
        print(
            f"{result['label']}: key={result['main_key']} "
            f"shape={result['shape']} dtype={result['dtype']}"
        )
    print(f"Wrote {DOC_PATH.relative_to(ROOT)}")
    return results


if __name__ == "__main__":
    main()
